### ISSUE TITLE
[Suggestion] Support connect to localhost when no connection is available

### ISSUE THREAD

**Issue by fatcloud** [getnamo/SocketIOClient-Unreal#109]
Hello thank you for this great plugin!

Currently I am using it for inter process communication between a python server and a unreal game.
Both process is running on my laptop so they do not need internet to communicate with each other.
Everything is working great except that when my laptop wifi is down, I cannot get the plugin connect to the server (at localhost).

I guess it happens this way because the plugin check for external connection before it tries to connect and it fails in my case. Thus I think it would be a good idea to add support for connecting to localhost when no connection is available.

I am using version plugin 0.95 with engine version 4.20

**Comment by getnamo** [comment]
Have you tried connect via e.g. 127.0.0.1 as address? That IP should be available even when wifi is down

**Comment by fatcloud** [comment]
127.0.01 does the trick. The answer just saved me a router before I ship my project to the client. Thanks a lot!
