### ISSUE TITLE
trying to emit event to Unreal client right when i disconnect from server

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/SocketIOClient-Unreal#219]
I am trying to emit an event that tells unreal client I have disconnected from server if i press control c. I am printing it on the console and it says the event is being emitted but it seems like it is not able to actually reach the client. How could i fix this?

**Comment by nitinjain442** [comment]
After i close the server, it's not going through the event tick one last time and that's the problem i think

**Comment by nitinjain442** [comment]
basically, im not able to set a variable to false after i disconnect from server even though it says i am emitting the event that does so.

**Comment by getnamo** [comment]
Not sure if Ctrl+c in certain terminals is a forceful quit. This may mean the server unravels before the event is actually emitted over network. If you can confirm the event can be received on another platform (e.g. JS client) then this might be fixable, if not it's likely not possible.
