### ISSUE TITLE
IOS Building Error V4_MAPPED

### ISSUE THREAD

**Issue by captainTvZx** [getnamo/SocketIOClient-Unreal#230]
`    F:\Unreal Projects\StackUp\Plugins\SocketIO\Source\ThirdParty\asio\asio\include\asio\ip\resolver_base.hpp:79:5: error: declaration shadows a variable in namespace 'asio::ip' [-Werror,-Wshadow]
        v4_mapped = ASIO_OS_DEF(AI_V4MAPPED),
    F:\Unreal Projects\StackUp\Plugins\SocketIO\Source\ThirdParty\asio\asio\include\asio\ip\address_v6.hpp:295:20: note: previous declaration is here
    enum v4_mapped_t { v4_mapped };
`

Please help !

**Comment by getnamo** [comment]
Version of plugin? v4_mapped suggests an underlying library include issue, check that you're using the latest commit for asio: https://github.com/getnamo/asio/tree/14dd8e3b0effdcf9da37bddcbfcd2ba822d3f58a you may need to add an ignore for shadow variable warning or #if around https://github.com/getnamo/asio/blob/14dd8e3b0effdcf9da37bddcbfcd2ba822d3f58a/asio/include/asio/ip/address_v6.hpp#L295

**Comment by lui-shex** [comment]
Is this issue resovled?

**Comment by finger563** [comment]
I also have this issue when building with 4.26 on a mac for ios

**Comment by finger563** [comment]
if you change lines 66-90 in `resolver_base.hpp` from:
```c++
#if (defined(PLATFORM_MAC) && PLATFORM_MAC)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wshadow"
#endif

  enum flags
  {
    canonical_name = ASIO_OS_DEF(AI_CANONNAME),
    passive = ASIO_OS_DEF(AI_PASSIVE),
    numeric_host = ASIO_OS_DEF(AI_NUMERICHOST),
    numeric_service = ASIO_OS_DEF(AI_NUMERICSERV),
    v4_mapped = ASIO_OS_DEF(AI_V4MAPPED),
    all_matching = ASIO_OS_DEF(AI_ALL),
    address_configured = ASIO_OS_DEF(AI_ADDRCONFIG)
  };

#if defined(PLATFORM_LINUX) && PLATFORM_LINUX
#pragma clang diagnostic pop
#endif

#if (defined(PLATFORM_MAC) && PLATFORM_MAC)
#pragma GCC diagnostic pop
#endif
```

to:

```c++
#if (defined(PLATFORM_MAC) && PLATFORM_MAC) || (defined(PLATFORM_IOS) && PLATFORM_IOS)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wshadow"
#endif

  enum flags
  {
    canonical_name = ASIO_OS_DEF(AI_CANONNAME),
    passive = ASIO_OS_DEF(AI_PASSIVE),
    numeric_host = ASIO_OS_DEF(AI_NUMERICHOST),
    numeric_service = ASIO_OS_DEF(AI_NUMERICSERV),
    v4_mapped = ASIO_OS_DEF(AI_V4MAPPED),
    all_matching = ASIO_OS_DEF(AI_ALL),
    address_configured = ASIO_OS_DEF(AI_ADDRCONFIG)
  };

#if defined(PLATFORM_LINUX) && PLATFORM_LINUX
#pragma clang diagnostic pop
#endif

#if (defined(PLATFORM_MAC) && PLATFORM_MAC) || (defined(PLATFORM_IOS) && PLATFORM_IOS)
#pragma GCC diagnostic pop
#endif
```

It will compile - note the only addition is the `|| (defined(PLATFORM_IOS) && PLATFORM_IOS)`

**Comment by smeeguel** [comment]
Confirming the change by @finger563 got iOS compiling and running again. 

My workflow using Windows 10 (remote compiling iOS on Macbook Air):
* Downloaded and unzipped 1.5.1 to my project's Plugins folder
* Deleted Binaries
* Edited 'Source/ThirdParty/asio/asio/include/asio/ip/resolver_base.hpp' with the above changes
* Launched project, forcing a repackage of the plugin
* Packaged iOS

**Comment by getnamo** [comment]
Fix merged in master and released as https://github.com/getnamo/socketio-client-ue4/releases/tag/1.5.5

**Comment by getnamo** [comment]
Working in latest marketplace

**Comment by captainTvZx** [comment]
@getnamo Thank u
