### ISSUE TITLE
Callbacks are cleared on FSocketIONative when Disconnect is called

### ISSUE THREAD

**Issue by peetonn** [getnamo/SocketIOClient-Unreal#255]
According to the documentation, one can disconnect at any point:

```
//You can also easily disconnect at some point, reconnect to another address
SIOClientComponent->Disconnect();
SIOClientComponent->Connect(TEXT("http://127.0.0.1:3000"));
```

However,  the `Disconnect()` call on `NativeClient` [clears all the callbacks](https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIONative.cpp#L102) but the only way callbacks are setup on `NativeClient` are through the `InitializeNative` [function](https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L76) which is protected.
This means that upon disconnect, the `USocketIOClientComponent ` callbacks on `NativeClient` are getting reset and there's no way to set them up again (calling `InitializeComponent` on a sister component that was statically initialized results in exception).

Is this a flaw or am I using the component wrong?

**Comment by getnamo** [comment]
Looking at https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIONative.cpp#L117 the internal callbacks get re-filled immediately, but the overwritten callbacks in https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L120 do get cleared and the clearing of ```EventFunctionMap``` appears to be another possible problem (you'd need to re-init all the event binds you make). This is quite a proper bug, I'm surprised it has lasted this long. Shows how much I've depended on uninitialize component for my disconnects.

We'd likely want to setup the component standard callbacks before connect automatically if cleared and probably maintain the old bound events until we uninitialize the component. I believe the original intent of clearing callbacks is so we won't receive additional messages after requesting a disconnect. I'll add this to the docket and try to find a good dev expectation.

In meantime your temp fix should allow you to continue work (you'll just need to rebind your own events from the looks of things)

**Comment by getnamo** [comment]
Likely fixed in: https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.2.0. Re-open if issue not fixed in latest release.
