### ISSUE TITLE
SocketIOClient component not connecting

### ISSUE THREAD

**Issue by srfoster** [getnamo/SocketIOClient-Unreal#259]
I have a simple socket.io server running:

```
const {Server} = require("socket.io"), 
server = new Server(8888);

server.on("connection", (socket) => {
    console.log(`Client connected [id=${socket.id}]`);
});
```

I've tested that the `console.log` fires when  a simple JS client connects:

```
const io = require("socket.io-client"),
ioClient = io.connect("http://localhost:8888");
```

But when I start an Unreal game with an actor that has a SocketIOClient component with auto-connect set to true, I get no console logs from the socket.io server. 

The only hint I have that something MIGHT be happening is that when I stop the socket.io server while the game is running, the Unreal logs say:

```
SocketIO Invalid appears to have lost connection, reconnecting attempt 0 with delay 5000
```

So it's maybe trying to do something, but from the socket.io server's perspective, the connection is not happening.  Why is the behavior with the ue4 client different from the js client?

**Comment by getnamo** [comment]
Make sure server socket.io version is 2.x or 1.x. update to support 3.x and 4.x is pending

**Comment by getnamo** [comment]
Closing due to age. Try latest plugin versions, re-open if issue persists.
