### ISSUE TITLE
Reconnect and events

### ISSUE THREAD

**Issue by ZeusLT** [getnamo/SocketIOClient-Unreal#262]
First time connecting works perfect, although after Disconnecting and attempting to Connect back Events stop working (OnConnect, OnGenericEvent etc) while logs in saved folder show that it actually manages to connect back fine. 

First connection:

> [2021.05.21-17.49.31:883][505]SocketIO: SocketIO Connected with session: u1Te1qo7vxx6KKsGAAEP
> [2021.05.21-17.49.31:883][505]SocketIO: SocketIO u1Te1qo7vxx6KKsGAAEP connected to namespace: /

![first](https://user-images.githubusercontent.com/22300013/119178769-71011f80-ba6e-11eb-80ec-eed2f9542402.PNG)

Disconnecting and Connecting again:

> [2021.05.21-17.52.01:153][466]SocketIO: SocketIO u1Te1qo7vxx6KKsGAAEP appears to have lost connection, reconnecting attempt 0 with delay 500
> [2021.05.21-17.52.01:389][480]SocketIO: SocketIO Connected with session: IRw_dLt60jK8pa-kAAEQ
> [2021.05.21-17.52.01:389][480]SocketIO: SocketIO IRw_dLt60jK8pa-kAAEQ connected to namespace: /

![reconnect](https://user-images.githubusercontent.com/22300013/119178727-647cc700-ba6e-11eb-96de-ba444308a29f.PNG)

The screenshot messages are just bound to the OnConnect and other Events. 
Note that I got new ID in logs but event "OnConnect" was never fired ingame.

![connect](https://user-images.githubusercontent.com/22300013/119179438-30ee6c80-ba6f-11eb-942c-ccb11eb152f7.PNG)

![BP](https://user-images.githubusercontent.com/22300013/119179177-eb31a400-ba6e-11eb-9531-334a4d898e99.PNG)

**Comment by Gurby** [comment]
Hello, I'm running onto the same kind of issue, can we be updated on this please ? Thank you :)

**Comment by ltsfwrs** [comment]
> 
> 
> Hello, I'm running onto the same kind of issue, can we be updated on this please ? Thank you :)
> 
> -> I was issuing the same kind of problem with a scoped connection, first connection was OK, but there was some vodoo stuff happening with the socket that didnt fully disconnect causing disconnect/reconnect on the 2nd attempt, leading to socket event owner mismatch.
> 
> **EDIT** : I have sorted it out : I have created en empty C++ class to get the project C++/BluePrint hybrid, and it seems to have fixed these weird behaviours.

Can you elaborate? I created an empty C++ class, have the "compile" button in the taskbar, compiled. It still can't reconnect.

**Comment by getnamo** [comment]
Likely related to https://github.com/getnamo/SocketIOClient-Unreal/issues/255. Possibly fixed in latest release, test and check.
