### ISSUE TITLE
(MacOS) Trying to use the plugin in UE4 Manually v1.6.0 for UE4.26 & 4.25 Is Not building.

### ISSUE THREAD

**Issue by KaSakee** [getnamo/SocketIOClient-Unreal#270]
OS: "MacOS Bigsur"

I'm trying to use v1.6.0 for UE4.26 & 4.25
IT says at first it's gonna rebuild the plugin because it has been built for a different version of UE
And then it fails to build.

"Test could not be compiled. Try rebuilding from source manually."

"Running Mono...

Found mono via known Mono.framework path
Running system mono/msbuild, version: Mono JIT compiler version 6.12.0.140 (2020-02/51d876a041e Thu Apr 29 10:44:55 EDT 2021)
/Users/Shared/Epic Games/UE_4.26/Engine /Users/Shared/Epic Games/UE_4.26/Engine/Binaries/Mac
Invalidating makefile for TestEditor (SocketIOClient.Build.cs modified)
@progress push 5%
Parsing headers for TestEditor
  Running UnrealHeaderTool "/Users/jisonhyun/Documents/Unreal Projects/Test/Test.uproject" "/Users/jisonhyun/Documents/Unreal Projects/Test/Intermediate/Build/Mac/x86_64/TestEditor/Development/TestEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/Users/jisonhyun/Library/Application Support/Epic/UnrealBuildTool/Log_UHT.txt" -installed
Reflection code generated for TestEditor in 5.8617296 seconds
@progress pop
Building TestEditor...
Performing 15 actions (5 in parallel)
[1/15] Compile Module.CoreUtility.cpp
[2/15] Compile Module.CoreUtility.gen.cpp
[3/15] Compile Module.SIOJson.cpp
[4/15] Compile Module.SIOJson.gen.cpp
[5/15] Compile Module.SocketIOLib.cpp
In file included from /Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Intermediate/Build/Mac/x86_64/UE4Editor/Development/SocketIOLib/Module.SocketIOLib.cpp:2:
In file included from /Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp:28:
/Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.h:207:5: error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
#if SIO_TLS
    ^
In file included from /Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Intermediate/Build/Mac/x86_64/UE4Editor/Development/SocketIOLib/Module.SocketIOLib.cpp:2:
/Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp:59:9: error: field 'm_reconn_made' will be initialized after field 'm_path' [-Werror,-Wreorder-ctor]
        m_reconn_made(0),
        ^
/Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp:77:5: error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
#if SIO_TLS
    ^
/Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp:252:5: error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
#if SIO_TLS
    ^
/Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp:629:5: error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
#if SIO_TLS
    ^
In file included from /Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Intermediate/Build/Mac/x86_64/UE4Editor/Development/SocketIOLib/Module.SocketIOLib.cpp:5:
/Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/sio_socket.cpp:34:5: error: 'DEBUG' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DEBUG || _DEBUG
    ^
/Users/jisonhyun/Documents/Unreal Projects/Test/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/sio_socket.cpp:34:14: error: '_DEBUG' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DEBUG || _DEBUG
             ^
[6/15] Compile Module.SIOJEditorPlugin.gen.cpp
[7/15] Compile Module.SocketIOClient.cpp
[8/15] Link UE4Editor-CoreUtility.dylib
7 errors generated.
[9/15] Compile Module.SocketIOClient.gen.cpp
[10/15] Compile Module.SIOJEditorPlugin.cpp
[11/15] Link UE4Editor-SIOJson.dylib" etc.. Can't get it because it's crashing before I can see it.

Even tho I'm using

socketio-client-v1.6.0-UE4.26.7z
On UE4.26.2

Any help <3

And a question can I use this plugin directly from the c++ code into the engine?

**Comment by KaSakee** [comment]
Even tho 25 is not compatible but I'm working with it and it's working??vthats weird

**Comment by getnamo** [comment]
I recommend rolling back to https://github.com/getnamo/socketio-client-ue4/releases/tag/1.5.5 until a marketplace release is made for v1.6 as Mac is currently untested and it's possible the new ```#if``` approached broke something?

**Comment by Lootheo** [comment]
Since i had to rush a macos build what i did to get around this compile issue was to explicitly define DEBUG and SIO_TLS on the sio_client_impl.cpp as 0 file after that I had to remove (sorry since i don't know the reason since i mostly do dev on windows) the m_path on the client_impl.cpp and put it as a direct definition on the .h file. 
std::string m_path;

to

std::string m_path = "socket.io";

idk if this helps.

**Comment by getnamo** [comment]
Latest marketplace (and likely github) releases build on Mac. Re-open if problem persists.
