### ISSUE TITLE
Query and headers are not transmitted

### ISSUE THREAD

**Issue by Amaratsu** [getnamo/SocketIOClient-Unreal#286]
Hello, for try send Query or Headers are not transmitted, check please.

**Comment by Amaratsu** [comment]
![image](https://user-images.githubusercontent.com/22033279/133587447-8510ec64-56a0-4d7a-8b62-8196d3194d14.png)

**Comment by Amaratsu** [comment]
but it works if sent from another client

**Comment by getnamo** [comment]
Make sure you use the connect with the query and headers set https://github.com/getnamo/socketio-client-ue4/blob/9765f50ffc5b0a4cde6486c8538cc72befe5c425/Source/SocketIOClient/Private/SocketIONative.cpp#L28

**Comment by Amaratsu** [comment]
> Make sure you use the connect with the query and headers set
> 
> https://github.com/getnamo/socketio-client-ue4/blob/9765f50ffc5b0a4cde6486c8538cc72befe5c425/Source/SocketIOClient/Private/SocketIONative.cpp#L28

I debugged and I see that the data comes in this line, but does not come to the server side.

**Comment by getnamo** [comment]
This is fixed in the latest version. Headers and Query to do forward to server correctly now. Grab https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.3.0
