### ISSUE TITLE
(UE5) Project remains in task manager after close

### ISSUE THREAD

**Issue by strmnn** [getnamo/SocketIOClient-Unreal#301]
(UE5) When forcefully closing the game(alt+f4, etc), the program will linger in the background.. steam thinks the game is still running, and the only way to close it is through the task manager.  This problem only occurs when sockets are being used.  Is there a way to force-close the sockets no matter the method of shutdown?  Thanks

**Comment by getnamo** [comment]
Test newest plugin version and let me know if the issue remains
