### ISSUE TITLE
Bug in v2.3.0 UE5

### ISSUE THREAD

**Issue by staskjs** [getnamo/SocketIOClient-Unreal#311]
Hello, I am moving to UE5, downloaded latest 2.3.0 version, I have probably found a bug trying to connect to server with Query object.
```
Assertion failed: Pair != nullptr [File:E:\UE5\Engine\Source\Runtime\Core\Public\Containers\Map.h] [Line: 656]

UnrealEditor_SocketIOClient!USIOMessageConvert::JsonObjectToFStringMap() [E:\Projects\sopsb\Plugins\SocketIOClient\Source\SocketIOClient\Private\SIOMessageConvert.cpp:200]
```

I narrowed my code down to this snippet that causes this error. It seems problem is with string values, other values don't cause crashes.

```
auto JsonObject = USIOJConvert::MakeJsonObject();
JsonObject->SetStringField("testString", "value");
USIOMessageConvert::JsonObjectToFStringMap(JsonObject);
```

**Comment by staskjs** [comment]
I think I found it

SIOMessageConvert.cpp:200
Changing from `ParamMap[Pair.Key] = Value->AsString();` to `ParamMap.Add(Pair.Key, Value->AsString());` fixed the problem.

**Comment by getnamo** [comment]
What was the bug message, or was the result just empty?
