### ISSUE TITLE
Auto disconnecting after aprox. 30 seconds,  CLOSE_REASON_NORMAL

### ISSUE THREAD

**Issue by krumiaa** [getnamo/SocketIOClient-Unreal#314]
Using this for a DRL openAI Gym setup, remote machine learning, just upgraded to UE 5.0 version win64, now it auto disconnects after 30 second, no error message, just "appears to have lost connection, reconnecting attempt 0 with delay 5000". It will reconnect, and start training again, but looses the connection after 30 seconds. Using this with an async eventlet server.  Any thoughts? Hers a link to source files. Was not happening in the 4.27 version
https://drive.google.com/file/d/198G2qN_RgIP-UZCih4Cqb0YDopIxNh1g/view?usp=sharing

**Comment by getnamo** [comment]
This uses embedded src in another plugin and may have modifications that are not the same as mainline. Please reach out to https://github.com/krumiaa/MindMaker repo with issue instead, or replace modules with mainline src that have been upgraded (e.g. v2.3.0 plugin).

**Comment by krumiaa** [comment]
Thanks, you were right, unstable behavior was because of some older python libraries that needed to be updated. Here are the culprits:  flask-socketio, python-socketio and python-engineio
