### ISSUE TITLE
Unable to build for UE5 Project

### ISSUE THREAD

**Issue by bapin93** [getnamo/SocketIOClient-Unreal#315]
When building for UE5 project I get the following error. It appears there is no `libOpus` in ThirdParty. Is this intentional? Per CUOpusCoder.h this is imported on most every platform.

I was able to get the project to build after removing my platform (PLATFORM_WINDOWS) from `#define WITH_OPUS (PLATFORM_WINDOWS || PLATFORM_MAC || PLATFORM_UNIX || PLATFORM_XBOXONE || PLATFORM_ANDROID)`

I don't particularly like this solution as it doesn't seem sustainable for future updates etc.

See build error from Visual Studio below:
<html>
<body>

Error | C1083 | Cannot open include file: 'ThirdParty/libOpus/opus-1.1/include/opus.h': No such file or directory | TestProject | C:\TestProject\Plugins\SocketIOClient\Source\CoreUtility\Public\CUOpusCoder.h | 7
-- | -- | -- | -- | -- | --

</body>
</html>

**Comment by getnamo** [comment]
I haven't seen this issue personally yet, but looking at https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/ThirdParty/libOpus/libOpus.build.cs#L21 it appears they've upgraded the lib version to 1.3 and it's possible the path is no longer valid (although looking at my own engine directory I still see both 1.1 and 1.3 present in canonical release). See if changing https://github.com/getnamo/SocketIOClient-Unreal/blob/master/Source/CoreUtility/Public/CUOpusCoder.h#L7 to ```#include "ThirdParty/libOpus/opus-1.3.1-12/include/opus.h"``` fixes the include for you. 

Note also that the opus coder is an optional utility class and you can safely delete both header and implementation along with the reference in the bp function library and it should compile.

**Comment by bapin93** [comment]
@getnamo Thank for the quick reply! When I look in https://github.com/getnamo/SocketIOClient-Unreal/tree/master/Source/ThirdParty I only see `asio rapidjson websocketpp`. I see this on both the repo and in the release download. Should I be seeing `libOpus` in that directory as well? 

I have found the Opus repository and it looks like I can compile from source. I suppose I could compile and drop the binaries into ThirdParty.

I also appreciate your suggestion of removing the files as it's an optional feature. It looks like Opus is a codec for transporting audio which I don't need at this point, but may be interesting for the future.

I guess my question is, should libOpus be part of the repository/release? If so, I would like to figure out why I'm not seeing it. If not, I seem to have two options: 

1) Remove the opus functionality.
2) Build libOpus myself and plop it in ThirdParty.

**Comment by bapin93** [comment]
After re-reading your comment, it looks like you are saying libOpus is supposed to be included as part of the Unreal ThirdParty, and not this plugins ThirdParty. Apologies for the misunderstanding. I will check your suggestions and report results. Thanks!

**Comment by getnamo** [comment]
Yep if you feel like making a PR, I'll merge it. Thanks for spotting the upgrade issue!

**Comment by bapin93** [comment]
@getnamo I can't push - "Access denied"

**Comment by bapin93** [comment]
Resolved by PR #316
