### ISSUE TITLE
UE4.27 | UE5 : SocketIO Invalid appears to have lost connection

### ISSUE THREAD

**Issue by ezawadzki** [getnamo/SocketIOClient-Unreal#324]
Hi,

I am trying to connect an Unreal SocketIO client example to a python websocket server that I developped.
The issue is that it loses the connection (see logs below).

Its works perfectly locally, without ssl.
I tested my python server through ssl with a web client, it works perfectly too.
It seems not working in SSL with Unreal Client, even I ticked the option "Use TLS libraries".

**Example version** :

https://github.com/getnamo/SocketIOClient-Unreal-Example/releases/tag/1.9.0

**Plugin Version** :

https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v1.10.0

**Unreal Version** : 4.27.2-18319896+++UE4+Release-4.27

```
PIE: Server logged in
PIE: Play in editor total start time 0.09 seconds.
SocketIO: SocketIO Invalid appears to have lost connection, reconnecting attempt 0 with delay 5000
LogSlate: Window 'ChatWindowActor' being destroyed
LogWorld: UWorld::CleanupWorld for World_1, bSessionEnded=true, bCleanupResources=true
LogSlate: InvalidateAllWidgets triggered.  All widgets were invalidated
SocketIO: SocketIO Invalid appears to have lost connection, reconnecting attempt 1 with delay 7500
SocketIO: SocketIO Invalid appears to have lost connection, reconnecting attempt 2 with delay 11250
```

Am I using the right version plugin with the right example ?

Thanks for your help,

Emilie

**Comment by ezawadzki** [comment]
Tested also with :

**Example version :**
Last master : sha - a507ecad21e3f030858eb369c1eb12172e084eed

**Plugin Version :**
https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.3.0

**Unreal Version :** 
Version: 5.0.1-19764885+++UE5+Release-5.0

Additionnaly I got this warning :
`LogUObjectGlobals: Warning: Failed to find object 'Class None.SIOJJsonObject'`

**Comment by getnamo** [comment]
Got an example snippet of the server code it's trying to connect to? Can you confirm the socket.io protocol version is V3 or V4+ on the server?

**Comment by ezawadzki** [comment]
Okay, I understand what happened. SocketIO is not using directly websockets but it is a layer on top.
So it isn't compatible with my server which use directly websocket (Django Channels).
Here more [info](https://stackoverflow.com/questions/40149418/django-channels-and-socket-io-client).

Thanks @getnamo for your help.
