### ISSUE TITLE
Android failed to load plugin

### ISSUE THREAD

**Issue by matteo411** [getnamo/SocketIOClient-Unreal#330]
SocketIOClient-Unreal-Example runs fine when built with UE5 on Windows Desktop but when I deploy to Android I get a message on launch:

"Plugin 'SocketIOClient' failed to load because module 'SIOJson' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project"

**Comment by getnamo** [comment]
followed https://github.com/getnamo/SocketIOClient-Unreal#packaging steps?

**Comment by matteo411** [comment]
OK. It now works on Android device after I did Tools>>New C++ Class, then closed UE5, built in VS2019, closed VS2019, then opened UE5 again and deployed to Android.
