### ISSUE TITLE
emit Can't guarantee 100 % success

### ISSUE THREAD

**Issue by LiXiaoRan** [getnamo/SocketIOClient-Unreal#333]
I use emit Can't guarantee 100 % success
![image](https://user-images.githubusercontent.com/9404112/185022439-afff7a28-f03f-46ba-8835-a23abba3294c.png)

**Comment by LiXiaoRan** [comment]
Can you tell me this how to solve

**Comment by getnamo** [comment]
Depends on connection and many other variables. Not enough information/context to give useful feedback. Re-open with more context relevant information.
