### ISSUE TITLE
Unable to connect from Oculus Quest 2 build

### ISSUE THREAD

**Issue by nateainsworth** [getnamo/SocketIOClient-Unreal#335]
I can connect from Oculus to the server fine while running the application locally off unreal on the PC. However, when I build the project, I can't connect. I'm using SSL on the server and HTTPS within the URL. I force HTTPS connections only, so the website doesn't allow HTTP, I've updated the Android manifest to enable Internet from advice on forums with the following lines
`<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

Looking through forums online, there's a common trend of people struggling with this, I believe one reason to be androids' restrictions on unsecured connections, which is why I'm using SSL. Although I have come across a few which have managed to get the connection working, there's no insight into how they managed it. 

If anyone has any ideas on how I could experiment to attempt to get this working, I would appreciate it.

**Comment by nateainsworth** [comment]
Okay, so if it helps, I've managed to get WebSockets to connect without any need for SSL or anything, so it's something with socket.io / the plugin stopping me from connecting to the server on an oculus build. I've used the following WebSocket code to get it working in case anyone else comes across the same issue https://github.com/chris-gong/websocket-client-example-ue5/blob/main/Source/WebSocketTest/WebSocketTestGameInstance.cpp However ideally I would like to get socket.io working as I prefer the plugin and library on my server-side talking to the website.

**Comment by getnamo** [comment]
Don't have a quest 2 to test this myself, do you know if builds to normal android targets such as an Android phone has the same issue?

This seems to hint at a config or SSL dependency copy problem (maybe pragma macros for ssl enabling fails on Oculus platform?)

**Comment by nateainsworth** [comment]
I don't have any other android devices it's a weird one as a setup on WebSockets doesn't require any SSL and it connects to wss://exampl.com just fine once built, but then I believe socket.io connects over HTTP instead and so maybe it does require SSL or something (I did test out connecting using ws, wss, HTTP and https). However, I did set this up, and with or without SSL couldn't get the plugin to work on the Oculus.

**Comment by getnamo** [comment]
My best guess is that the oculus 2 platform is not considered android in pragma/build.cs and is getting code excluded, check the platform strings required, those would need to be added for code checks in pragmas and build.cs filters.

**Comment by getnamo** [comment]
Check if https://github.com/getnamo/SocketIOClient-Unreal/issues/348 fixed this issue

**Comment by jorgearroyop** [comment]
I'm having the same problem. I'm using Unreal 5.4.4 and SocketIOClient-Unreal v2.8.
I have already enabled on Unreal Platform Android the following settings: android.permission.INTERNET, android.permission.ACCESS_NETWORK_STATE and android:usesCleartextTraffic="true".

I have also tested locally with a Python http server and with an https server (with self signed certificate). 

Everything works fine when running on the Unreal Engine Editor but as soon as I build the package it doesn't work on the Meta Quest 3.

If someone has found a solution please share it :)
