### ISSUE TITLE
"Project could not compile, try rebuilding from source"

### ISSUE THREAD

**Issue by kap7475** [getnamo/SocketIOClient-Unreal#337]
Hi, so I don't know if I am doing something horribly wrong but I can't seem to get this plugin to work at all. Every time I attempt to open Unreal, it says "Project could not be compiled, try rebuilding from source manually". I'm working with 4.27, so I am using the 4.27 backport branch and get this issue. 

![image](https://user-images.githubusercontent.com/76821800/188111342-4351c90e-c35b-4bcd-b7c5-dc7963bc7828.png)
I click Yes to the image above and 5 seconds later get this:
![image](https://user-images.githubusercontent.com/76821800/188111424-3ca1c5c2-184f-4f79-a994-ae32ed35f848.png)

My folder structure seems to be fine, I have implemented plugins before and I don't think I've done anything differently.
![image](https://user-images.githubusercontent.com/76821800/188111597-6d832239-7ac5-4692-a3ba-daee77097402.png)

The error I get when I hit F5 in VS is this: 
![image](https://user-images.githubusercontent.com/76821800/188122641-6ef80256-0ddd-4339-a6ec-5c8357695ea5.png)

I've tried using the git clone command but I only get the ue5 repo which isn't what I am using. 
I have also tried adding the module dependencies as my project does use C++ but that also didn't solve my issue. 

Any help? Thanks :)

**Comment by spoiler335** [comment]
I have a C++ project in 5.1 and I am try to Update it to 5.4 and still get similar error
