### ISSUE TITLE
Probably wrong field name bShouldSkipCertificateVerification and wrong default value

### ISSUE THREAD

**Issue by polidenis** [getnamo/SocketIOClient-Unreal#338]
`virtual TSharedPtr<FSocketIONative> NewValidNativePointer(const bool bShouldUseTlsLibraries = false, const bool bShouldSkipCertificateVerification = true);`

I suggest to rename _bShouldSkipCertificateVerification_ to _bShouldVerifyTLSCertificate_(this name is used in USocketIOClientComponent and also in FSocketIONative) and change default value to false. I was trying to use plugin with C++ FSocketIONative approach and had issue with this field. 

That code will not work with https/wss cause in fact it has _bShouldVerifyTLSCertificate_ = true(**NOT _bShouldSkipCertificateVerification_  = true**), which is not implemented yet. (https://github.com/getnamo/SocketIOClient-Unreal/issues/303)
`Socket= ISocketIOClientModule::Get().NewValidNativePointer(true);`
`Socket= ISocketIOClientModule::Get().NewValidNativePointer(true, true);`
Only this will work with https/wss
`Socket= ISocketIOClientModule::Get().NewValidNativePointer(true, false);`

**Comment by getnamo** [comment]
Valid comment on API, if you make a pull request with the changes I'll merge them after review.

**Comment by polidenis** [comment]
Okay then, here is PR https://github.com/getnamo/SocketIOClient-Unreal/pull/339
