### ISSUE TITLE
Cant connect to server.

### ISSUE THREAD

**Issue by boonmaya** [getnamo/SocketIOClient-Unreal#348]
I upgrade plugin to [v2.4.0 Release for UE5.0](https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.4.0)

after upgrade I cannot connect to my server.

3.2.5 Can connect via Connecct with param.

**Comment by getnamo** [comment]
Do you have additional information like socket.io protocol version used, http or https address, any logs from failed connection?

**Comment by boonmaya** [comment]
After I check out Commit: c79a43761bf5d4b88ccba538cc93bdea059184ca [c79a437]

Unreal PC can connect to my https server already.

But I want to ask you, Android cannot use socket.io on https  right? Because when I build my game to android, it can connect socket.io only http  if I connect to https it will be get in to connect problem events.

Do you have plan to fix it?

**Comment by boonmaya** [comment]
Hi @getnamo

**Comment by getnamo** [comment]
I made a quick untested push with the platform added back in: https://github.com/getnamo/SocketIOClient-Unreal/commit/fd7cb7aec136bcd6d67690159b816739eb7c3c24

Pull latest and rebuild the plugin and let me know if the android https works.

**Comment by boonmaya** [comment]
I use your code to enable TLS on android 
It usable now. But try to test more. Thanks. 
But I dont know if it effect to another plugin or not. because I found crash on android's sendbird chat. 
I will try to test more.
