### ISSUE TITLE
I can't open SocketIOClient-Unreal-Example on MacBook Pro M1 Pro 2021 (MacOS Monterey 12.3.1)

### ISSUE THREAD

**Issue by JetFire01** [getnamo/SocketIOClient-Unreal#349]
I did this project a year ago on my windows, now I have a desire to try it out on my new macbook, but the problem is that I can't open it. Help what should I do??? Here is what the unreal engine writes when opening a project.
<img width="328" alt="Screenshot 2022-11-01 at 20 11 59" src="https://user-images.githubusercontent.com/109907057/199297338-5b908bde-b05f-4b2e-ae12-e868c851386e.png">
<img width="372" alt="Screenshot 2022-11-01 at 20 12 21" src="https://user-images.githubusercontent.com/109907057/199297395-25990cde-92f2-4205-843e-a71a883647e5.png">

**Comment by getnamo** [comment]
Answered here: https://github.com/getnamo/SocketIOClient-Unreal-Example/issues/9#issuecomment-1301184622, continue discussion there
