### ISSUE TITLE
Fails to compile for Oculus-VR UE5 build

### ISSUE THREAD

**Issue by matteo411** [getnamo/SocketIOClient-Unreal#350]
The client works awesome for the main UE5.0.3 release but won't compile for me on the Oculus-VR branch of UE5.0.3:
https://github.com/Oculus-VR/UnrealEngine/tree/oculus-5.0

I've tried using the plugin from Marketplace as well as compiling from source from this github and both give the same error. The UDP-Unreal client seems fine its just the SocketIO stuff will make the packaging compile fail:

Logs:
```
PackagingResults: Warning: Plugin 'SocketIOClient' is not compatible with the current engine version (5.0.0)
UATHelper: Packaging (Android (ASTC)): LogLinker: Warning: VerifyImport: Failed to find script package for import object 'Package /Script/CoreUtility'
UATHelper: Packaging (Android (ASTC)): LogBlueprint: Error: [AssetLog] D:\Unreal Projects\OculusTest2\Content\UDPReceiverBlueprint_3.uasset: [Compiler] In use pin  In Bytes  no longer exists on node  Conv Bytes to String . Please refresh node or break links to remove pin. from Source: /Game/UDPReceiverBlueprint_3.UDPReceiverBlueprint_3
UATHelper: Packaging (Android (ASTC)): LogBlueprint: Error: [AssetLog] D:\Unreal Projects\OculusTest2\Content\UDPReceiverBlueprint_3.uasset: [Compiler] In use pin  Return Value  no longer exists on node  Conv Bytes to String . Please refresh node or break links to remove pin. from Source: /Game/UDPReceiverBlueprint_3.UDPReceiverBlueprint_3
UATHelper: Packaging (Android (ASTC)): LogBlueprint: Error: [AssetLog] D:\Unreal Projects\OculusTest2\Content\UDPReceiverBlueprint_3.uasset: [Compiler] Could not find a function named "Conv_BytesToString" in 'UDPReceiverBlueprint_3'.
UATHelper: Packaging (Android (ASTC)): Make sure 'UDPReceiverBlueprint_3' has been compiled for  Conv Bytes to String from Source: /Game/UDPReceiverBlueprint_3.UDPReceiverBlueprint_3
```

**Comment by getnamo** [comment]
Sounds like you need to rebuild the plugin for your platform. Pull latest from github and place it in your project directory and compile (assuming it's mixed/c++ it will compile the plugin along with project). Then packaging should work. See https://github.com/getnamo/SocketIOClient-Unreal#github

**Comment by matteo411** [comment]
It was already a mixed/c++ project. I found a solution to the compile issue. I edited the SocketIOClent.uplugin text file line 5 from

	"EngineVersion": "5.0.0",

to

	"EngineVersion": "5.0.3",
