### ISSUE TITLE
Very long period between sending packets

### ISSUE THREAD

**Issue by ProudFaceOfSUiR** [getnamo/SocketIOClient-Unreal#351]
I am using Emit Bytes node to send some values to python script running on the same machine and I am getting 0.33 sec delay between packets. I've tried running it on Windows and Linux, problem stays the same. Adjusting buffer size and tick interval does not help

**Comment by ProudFaceOfSUiR** [comment]
Oh, sorry, Unreal just updates 3 fps when it's not active, my bad)

**Comment by getnamo** [comment]
The setting to adjust that behavior should be in editor settings: https://answers.genvidtech.com/articles/51/low-framerate-in-ue4editor.html
