### ISSUE TITLE
BUILD FAILED “PackagingResults: Error: Unknown Error”  by UE 5.1，plugin version is 2.5.0, please help me

### ISSUE THREAD

**Issue by LiXiaoRan** [getnamo/SocketIOClient-Unreal#353]
![image](https://user-images.githubusercontent.com/9404112/202368874-74f33286-91f8-45c9-b233-c12e16e049e9.png)
as top picture, When I was in project packaging packaging error occurred, this is first error info.

**Comment by getnamo** [comment]
What platform are you packaging for? Are you using the FSIOJNamed type in blueprints? Try recompiling and saving mentioned blueprint. Try a clean rebuild

**Comment by LiXiaoRan** [comment]
> What platform are you packaging for? Are you using the FSIOJNamed type in blueprints? Try recompiling and saving mentioned blueprint. Try a clean rebuild

ok, i will repair this problem, this is due to the fact that I trans a double number to [set number field] blueprint node, i modify this node params as double from float

**Comment by LiXiaoRan** [comment]
> What platform are you packaging for? Are you using the FSIOJNamed type in blueprints? Try recompiling and saving mentioned blueprint. Try a clean rebuild

very thanks for U replay

**Comment by getnamo** [comment]
Great, thanks for letting me know what the issue was.
