### ISSUE TITLE
Build failing in Unreal 5.2 due to SocketIOLib "sio_client_impl.h" 

### ISSUE THREAD

**Issue by Qianlixun** [getnamo/SocketIOClient-Unreal#380]
“websocketpp/config/asio_client.hpp”: No such file or directory

**Comment by getnamo** [comment]
if cloning from git, pull with ```--recurse-submodules```, see https://github.com/getnamo/SocketIOClient-Unreal#via-git-clone

**Comment by getnamo** [comment]
Latest release https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.7.1 should work. Re-open if issue persists.
