### ISSUE TITLE
Unreal Engine version 5.3

### ISSUE THREAD

**Issue by marister** [getnamo/SocketIOClient-Unreal#389]
I am getting errors when compiling my self 😢 
Is there an estimation when you could possibly release the 5.3 version?

THANK YOU IN ADVANCE!

**Comment by marister** [comment]
Ah this pull request actually looks like the errors I am getting when compiling.
Any idea if this is the answer or if something similar will be merged?
https://github.com/getnamo/SocketIOClient-Unreal/pull/387

**Comment by getnamo** [comment]
5.3 release available here: https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.7.0

**Comment by getnamo** [comment]
A couple build issue were squashed, now updated in https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.7.1. Marketplace 5.3 pending.

**Comment by getnamo** [comment]
Marketplace 5.3 is live.
