### ISSUE TITLE
Add OpenSSL support

### ISSUE THREAD

**Issue by getnamo** [getnamo/SocketIOClient-Unreal#39]
Current libs do not have openssl compiled in. Need to check the settings to get openssl built for socket.io client cpp.

Edit: Current SSL support available in https://github.com/getnamo/socketio-client-ue4/tree/ssl branch

**Comment by getnamo** [comment]
might be related to why https://github.com/getnamo/socketio-client-ue4/issues/14 is occuring

**Comment by jostster** [comment]
@getnamo does this mean https is not supported?

**Comment by getnamo** [comment]
I believe so, but some tests to confirm would be useful.

**Comment by jostster** [comment]
@getnamo yes, we moved our server to https. Socket.io then stopped working. We then opened up another instance on regular http port 80 and it works fine. It seems that inside the socketio.lib file is where the issue is, yet we don't have the pdb's to debug in there further. Do you have an ETA on when you will have an ssl supported version?

**Comment by getnamo** [comment]
Thanks for confirming!

I don't currently have an eta on SSL, but now that I know there is demand for it I'll add it to the list. That said the underlying .lib that gets compiled is also open source with it's repo here: https://github.com/getnamo/socketio-client-prebuild which has the cmake script shown here: https://github.com/getnamo/socket.io-client-cpp/blob/bfa0a53a4851cbbd56d4606c6d6fbed3f81a964b/CMakeLists.txt#L51 if I remember correctly, I didn't have OPENSSL library installed in the correct location on my computer when I was building the socket.io library. based on the above script, it does appear that everything else is already ready for it. If you need it badly, consider contributing by updating the underlying .lib to include the OpenSSL libs!

Also as a side note you can get the .pdbs easily by compiling the plugin in a UE4 c++ project, which will recompile the plugin and generate the .pdbs.

**Comment by anadin** [comment]
I'm gonna jump in on this one - I'm at a bit of a loss, I do have openSSL installed so I think the boost libs compiled ok. (macOS). I expect and need to use ws:// or wss:// for the URL not sure where to make that change :(

**Comment by getnamo** [comment]
Note to self: with refactor, we can likely use the built-in openssl module: https://github.com/EpicGames/UnrealEngine/tree/release/Engine/Source/ThirdParty/OpenSSL. TBC

**Comment by getnamo** [comment]
Note to self: merge e.g. https://github.com/socketio/socket.io-client-cpp/pull/137 into base

**Comment by The12MT** [comment]
What is the current status of tls support?

**Comment by dobby5** [comment]
Are there any news already?

**Comment by getnamo** [comment]
Still waiting to find time to build an SSL server with a certificate to use for AB tests.

There have been some early work done, but the blocker has been the certificate process. Branch for this work is found at: https://github.com/getnamo/socketio-client-ue4/tree/issue-39

**Comment by dobby5** [comment]
I have to ask again do you only need a socketio server with https connection? I can provide that for you.

**Comment by getnamo** [comment]
@dobby5 that would likely be helpful, current blocker is setting up an SSL server with socket.io server running so it can be tested against.

**Comment by dobby5** [comment]
Okay good.

I don't like to make my server IP public. Would you like to send me an email. Then I will send you the server address.

Dobby5nk@gmail.com

**Comment by zerotri** [comment]
@getnamo Do you still need a public https socketio server to test against? I can throw one together pretty quickly.

**Comment by dobby5** [comment]
Hello, Jan,

I hope I'm not disturbing you. I just wanted to ask you if there's anything
I can do to help?

Your plugin helps me and a small team to implement our chat and we wanted
to start the work there. Because of the question one can help you speed
that up?

Greetings
Dobby

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Sa., 28. März 2020 um 05:12 Uhr schrieb Wynter Woods <
notifications@github.com>:

**Comment by getnamo** [comment]
I've been swamped in the past few weeks, still trying to find some time for this issue. If there are any decent C++ programmers, they could help patch in the openssl module based on info in this issue and https://github.com/getnamo/socketio-client-ue4/issues/72#issuecomment-371956821. Code contributions are always welcome.

**Comment by brittanft** [comment]
@getnamo Is there any update regarding SSL support? This is crucial to my project and the existing workaround seems to be outdated. If not, is there an email I can reach you at or something?

**Comment by getnamo** [comment]
It's still on the docket. I need to schedule time to specifically address this issue. No ETA atm, will ping here when I find time.

**Comment by cheburashkalev** [comment]
we are still waiting for wss and https

**Comment by brittanft** [comment]
@cheburashkalev I believe this is how you support SSL (ONLY SSL, this will break non-SSL): In the files sio_client_impl.h and sio_client_impl.cpp you want to add "#define SIO_TLS 1" near the top of the file. Then add "OpenSSL" to the PublicDependencyModuleNames and PrivateDependencyModuleNames of SocketIOLib.Build.cs. There might be a few compilation issues which you'll have to solve. Good luck.

**Comment by The12MT** [comment]
I have just moved to plain websockets. Using this plugin without tls is just careless and dangerous. I wonder how it got such a good rating. Very sad.

**Comment by brittanft** [comment]
@The12MT I have the plugin working with tls using the steps I provided above. Just takes a bit of tinkering lol. No need to bash the merits of this project. Mostly has to do with the awkward socket.io port to c++, completely unrelated to getnamo's contributions.

**Comment by Nepoxx** [comment]
> I have just moved to plain websockets. Using this plugin without tls is just careless and dangerous. I wonder how it got such a good rating. Very sad.

You know what's sad? The fact that you expect an open source project to cater to **your** needs and are not willing to contribute anything in return. The author is taking his own personal time to work on this, you have no rights no complain about what they do or don't do.

**Comment by The12MT** [comment]
> > I have just moved to plain websockets. Using this plugin without tls is just careless and dangerous. I wonder how it got such a good rating. Very sad.
> 
> You know what's sad? The fact that you expect an open source project to cater to **your** needs and are not willing to contribute anything in return. The author is taking his own personal time to work on this, you have no rights no complain about what they do or don't do.
> 
> You are free to implement this and I'm sure they would be more than happy to look at your PR.

Wrong. He is selling his work on the unreal marketplace stating that there will be ssl very soon ;D I have my own projects and don't care at all about this project anymore since I "have moved to websocket".

**Comment by LucasFoucault** [comment]
Hi everyone !

First, thanks you to @getnamo for your great work. This plugin is very useful and easy to setup.

These last days I try to make the code support SSL but I encounter several pitfalls. I added the code mentionned by @brittanft and wiped out some compalition issues but it still not working.

I get always this error : "SocketIO Invalid appears to have lost connection, reconnecting attempt 0 with delay 5000".
By digging into the problem, I have noticed this error : "TLS handshake failed".

My knowledge in this field is pretty bad... Can someone help me understand what I'm doing wrong?

**Comment by LucasFoucault** [comment]
Finally, I managed to solve my problem!

I solved the above problem by modifying the generic TLS version in the `on_tls_init` function.
I upgraded to TLS 1.2 instead of the original 1.0 version :
`context_ptr ctx = context_ptr(new asio::ssl::context(asio::ssl::context::tlsv12));`

Now, the plugin works perfectly! I can receive all events from a remote browser.

**Comment by Zananok** [comment]
I am having an issue on the build process:
`openssl_types.hpp(22): Error C1083 : Cannot open include file: 'openssl/conf.h': No such file or directory`
If i change to be a full path, the first include of 'conf.h' fails with the same error, just that its for openssl/bio.h

Really appreciate any help

**Comment by peetonn** [comment]
If anyone's interested, I spent last couple of days adding OpenSSL support to this plugin. Check `tls` branch of this fork -- https://github.com/peetonn/socketio-client-ue4/tree/tls. Last commits shall explain you my story of getting OpenSSL to work.

**Comment by getnamo** [comment]
@peetonn That looks great, do you know if your implementation disables non-ssl connections or do both type of connections work?

**Comment by peetonn** [comment]
> @peetonn That looks great, do you know if your implementation disables non-ssl connections or do both type of connections work?

I haven't tested it, but I suspect it disables unencrypted... I'll update if I get a chance to test.

**Comment by liorneo** [comment]
yeah he fucked it up with the none SSL, but who cares?
this thing worth nothing none ssl. this guy rocks!!
thanks man :)

**Comment by dobby5** [comment]
Atm i could not make OpenSSL switchable until now, but we can also use the OpenSSL integration from the UE4.

Besides the fact that it saves us some data, it should now work on Mac, IOS, Windows 32 and 64bit.

https://github.com/dobby5/socketio-client-ue4/tree/tls

**Comment by getnamo** [comment]
This is great option, awesome work.

Until we get this to work via url swap (https->ssl, http->standard) without compile changes, I'll leave it in an ssl branch https://github.com/getnamo/socketio-client-ue4/tree/ssl. This way just swapping the branch in git, will let you have the SSL variant of the plugin until it matures in master.

**Comment by staskjs** [comment]
Is there any chance of TLS support making it into main branch soon?

I tried setting it up from the ssl branch, it seems to work properly in editor, but it just disconnects in packaged build `SocketIO Disconnected l4R3LEWmbEssJssCAAAG reason: CLOSE_REASON_NORMAL` and nothing more. Does not reconnect. How do I fix this?

**Comment by seesemichaelj** [comment]
@getnamo @dobby5 I see some work was done in `ssl-dev` roughly 10 months ago to figure out swapping between SSL and not without recompiling; what work is necessary to get this over the finish line?

**Comment by seesemichaelj** [comment]
After some further investigation, it seems like `ssl-dev` had the initial work for swapping TLS/SSL and not, but the code wasn't fully integrated.

I have a working swapping branch over at https://github.com/IncantaGames/socketio-client-ue4/tree/ue5, with the majority of the changes to get `ssl-dev` working in https://github.com/IncantaGames/socketio-client-ue4/commit/71c08f762e800cd7ec53ebacc5b0fe83ea454afb. Note, that branch is not mergeable into `ssl-dev` as I rewrote a commit that changed a bunch of whitespace/formatting (so I can figure out what was added).

I've tested both modes with a `socket.io` nodejs server (with a self signed certificate). There's work that needs to be done to figure out how to verify certificates, but I've given a checkbox to turn on/off verification.

Let me know if you'd like me to make a pull request out of this.

**Comment by getnamo** [comment]
The criteria to get an ssl branch merged is that both http and https work. I believe ssl-dev had changes that made only https work and broke http support. If you have a working branch with both without code changes, I'd definitely be interested in merging the work.

**Comment by seesemichaelj** [comment]
Ok, I'll look into separating my work into an MVP branch that's mergeable into `master`

**Comment by staskjs** [comment]
Will this branch be viable for ue5? ssl is highly important feature, would be great to have it in ue5

**Comment by seesemichaelj** [comment]
> Will this branch be viable for ue5? ssl is highly important feature, would be great to have it in ue5

@staskjs if I actually remember to get my PR in 😅, it will support UE5 and UE4.

**Comment by cheburashkalev** [comment]
> > Will this branch be viable for ue5? ssl is highly important feature, would be great to have it in ue5
> 
> @staskjs if I actually remember to get my PR in 😅, it will support UE5 and UE4.

https://github.com/getnamo/SocketIOClient-Unreal/pull/302

Try this)

**Comment by staskjs** [comment]
Thanks guys, going to check this out as soon as other plugins to update to ue5 and I can boot my project up

**Comment by cheburashkalev** [comment]
> 
![image](https://user-images.githubusercontent.com/47310777/162325107-170605a8-0e0e-4562-be4a-4382548b3806.png)
but there are changes there

**Comment by seesemichaelj** [comment]
Alright, thanks @staskjs for the reminder, but I finally was able to get my PR submitted: #304

**Comment by getnamo** [comment]
Will review shortly and merge if it passes my internal tests

**Comment by getnamo** [comment]
Release with @seesemichaelj pull request available here: https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.1.0. Please do test and let us know if it works as intended. See https://github.com/getnamo/SocketIOClient-Unreal#httpsssl for basic API
