### ISSUE TITLE
Not working at all in 5.3....

### ISSUE THREAD

**Issue by LogicPy** [getnamo/SocketIOClient-Unreal#394]
The following modules are missing or built with a different engine version:

  SocketIOClient
  SIOJson
  SocketIOLib
  CoreUtility
  SIOJEditorPlugin

Would you like to rebuild them now?

"could not be compiled. Try rebuilding from source manually."

Great job with 5.3. If only I could compile it once at least.... But, nope. How to fix this issue from a clean project?

**Comment by naniBox** [comment]
Did you get it working?

Can you at least describe the steps you took to get it working for people with similar problems?
