### ISSUE TITLE
Inclusion with build file for 5.3?

### ISSUE THREAD

**Issue by LogicPy** [getnamo/SocketIOClient-Unreal#395]
I've been editing the build files constantly trying to figure out how to compile this thing from a clean project. Here are my errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'Launch/Resources/Version.h': No such file or directory	Llolms_local_ai_2	E:\UE_5.3\Llolms_local_ai_2\Plugins\SocketIOClient-Unreal-2.7.0\Source\CoreUtility\Private\CUBlueprintLibrary.cpp	14	
Error	C1083	Cannot open include file: 'websocketpp/client.hpp': No such file or directory	Llolms_local_ai_2	E:\UE_5.3\Llolms_local_ai_2\Plugins\SocketIOClient-Unreal-2.7.0\Source\SocketIOLib\Private\internal\sio_client_impl.h	38

**Comment by LogicPy** [comment]
Heh, heh. I've finally resolved this issue by using the direct path to include the file such as:

#include "E:/UE_5.3/Engine/Source/Runtime/Launch/Resources/Version.h"

Thanks anyway friends, and thank you for releasing this for the most recent version of Unreal on your GitHub. You didn't have to, but you did it anyway. I respect and love that.

**Comment by getnamo** [comment]
If you pull from github, make sure you recurse submodules, see https://github.com/getnamo/SocketIOClient-Unreal#via-git-clone otherwise use the releases (.7z link) which should work out of the box.

**Comment by getnamo** [comment]
Fixed in https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.7.1
