### ISSUE TITLE
Unable to build for MacOS 14 (Sonova) Unreal Engine 5.2

### ISSUE THREAD

**Issue by Raibatsu** [getnamo/SocketIOClient-Unreal#396]
Unable to build the plugin version 2.6 for MacOS 14 (Sonova) that is running Unreal Engine 5.2.1. 
It would previously throw errors regarding std not being added before the move command: 
`Public/sio_message.h:208:38: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
            :message(flag_string),_v(move(v))
                                     ^
                                     std::`

After adding all these std namespaces, these errors go away, but I get prompted with a flurry of other errors. I have attached the log with this issue. I hope it proves to be useful:
[UBT-UnrealGame-Android-Development.txt](https://github.com/getnamo/SocketIOClient-Unreal/files/12866452/UBT-UnrealGame-Android-Development.1.txt)

**Comment by getnamo** [comment]
fixed in https://github.com/getnamo/SocketIOClient-Unreal/releases/tag/v2.7.1
