### ISSUE TITLE
UE5.3.2 packaging error on windows platform

### ISSUE THREAD

**Issue by jeff-song1122** [getnamo/SocketIOClient-Unreal#401]
LogClass: Error: EnumProperty FSIOJ_NamedType::Type is not initialized properly. Module:SIOJEditorPlugin File:Public/SIOJ_BreakJson.h
I used the latest version 2.7.1

**Comment by jeff-song1122** [comment]
Sovled by using maketplace version!

**Comment by UrbanSam** [comment]
I've stumbled upon this issue, using latest from marketplace v2.7.3. Packaging for window platform.
