### ISSUE TITLE
How to implement Emit method to support MessageList?

### ISSUE THREAD

**Issue by CheaterScript** [getnamo/SocketIOClient-Unreal#407]
Hi,
The socket.io server framework I'm using includes not only events but also a path. In JavaScript, the call looks like this:
```javascript
socket.emit('call', 'v1.game.hello', {a:111,b:333}, (err,res)=>{
	console.log(err, res)
})
```
After a rough look at the source code, I didn't see support for the MessageList interface. I wonder if the current plugin doesn't support this usage. How can I implement it?

**Comment by getnamo** [comment]
Can you point to socket.io protocol documentation of your requested feature?

**Comment by CheaterScript** [comment]
I haven't found an exact example, but it should be similar to the image below：
![image](https://github.com/getnamo/SocketIOClient-Unreal/assets/7920569/4c35a880-716d-4bef-b333-5400934657c7)
This is what the JavaScript client looks like after encoding:
![image](https://github.com/getnamo/SocketIOClient-Unreal/assets/7920569/aaaca3d4-4958-48ff-99ce-1306d86634ea)

**Comment by CheaterScript** [comment]
![image](https://github.com/getnamo/SocketIOClient-Unreal/assets/7920569/fe070beb-79fb-4302-af9d-eb0d38e2b898)

**Comment by getnamo** [comment]
This looks like just a multiparam message which is supported via second param on function, see e.g. https://github.com/getnamo/SocketIOClient-Unreal?tab=readme-ov-file#emit-with-callback and https://github.com/getnamo/SocketIOClient-Unreal?tab=readme-ov-file#binding-events-to-functions

**Comment by CheaterScript** [comment]
Thank you for your response. My question wasn't very clear. The main issue I'm facing is not knowing how to send a MessageList through the Emit method. I've attempted to implement an interface myself, and it looks like this: 
```cpp
void USocketIOClientComponent::EmitMessages(const FString& EventName, const TArray<TSharedPtr<FJsonValue>>& Messages, const FString& Namespace)
{
	if (Messages.Num() <= 0)
	{
		//Set the message is not null
		TSharedPtr<FJsonValue> JsonMessage = MakeShareable(new FJsonValueNull);

		NativeClient->Emit(EventName, JsonMessage, nullptr, Namespace);
		return;
	}

	sio::message::list* MessageList = new sio::message::list();

	for (int i = 0; i < Messages.Num(); i++)
	{
		MessageList->push(USIOMessageConvert::ToSIOMessage(Messages[i]));
	}

	NativeClient->EmitRaw(EventName, *MessageList, nullptr, Namespace);

	delete MessageList;
}
```
I'm not sure if there's already a solution like this in the plugin, but my current implementation seems to meet my needs.
Thank you for all your assistance.

**Comment by getnamo** [comment]
It seems I misunderstood, I do believe this variant:
https://github.com/getnamo/SocketIOClient-Unreal/blob/e6fb5dbea25e290bcfae32c60707757a48cf55d7/Source/SocketIOClient/Public/SocketIOClientComponent.h#L429

Does the same, but if does not, feel free to open a pull request and I can merge the feature to mainline.

**Comment by CheaterScript** [comment]
I tested the method above and didn't get the expected result: 

![image](https://github.com/getnamo/SocketIOClient-Unreal/assets/7920569/01292aca-4b9e-4788-892b-78e9acf258bd)

The correct result should be: 
```Javascript
["call","foo","bar"]
```
Implementing EmitMessagesWithCallback seems to be quite complex, and I'm not very proficient in C++. I'm worried that I might introduce bugs and may not be able to provide a fully functional PR.

**Comment by getnamo** [comment]
Interesting, it does seems like the plugin is missing the implementation then. If you open a pull request with your current implementation, I'll apply patches to it to fit other methods before merging; it will give me a base scaffold to apply the rest of the functionality.
