### ISSUE TITLE
Can you authorize me to use your network plugin in my plugin submission to the Unreal Marketplace?

### ISSUE THREAD

**Issue by LogicPy** [getnamo/SocketIOClient-Unreal#409]
Hi friend. I've been developing an ai based plugin that I'd really like to sell on the Unreal Marketplace, and I've used your beautiful plugin as the network based communication source. And I'd love to upload my plugin to the marketplace powered by your socket.io network plugin you've built super perfectly and have released to the GitHub community. The best part of my plugin that I'd like to sell on the Marketplace, is that it's going to allow the Unreal community to use any ai model within their game engine, any GGML or GPTQ model from HuggingFace or GitHub.

I hope you consider it. Here's a video of me using the plugin too if you want evidence for its existence for right now:
https://www.youtube.com/watch?v=FpL0Ixs4FnU

The plugin I've built communicates using your plugin to the Lollms ai framework and it enables a user to communicate to any loaded ai model within the Unreal game engine.

Thanks friend!

**Comment by getnamo** [comment]
You don't need my authorization, it's MIT licensed so you already have the authority. That said I appreciate the reach out and wish you the best of luck with your cool project!

**Comment by LogicPy** [comment]
Beautiful! Thanks for your help, friend!
